export interface SupabaseListingRowDTO {
  id: string;
  title: string;
  description?: string | null;
  price: number | string;
  category?: string | null;
  condition?: string | null;
  nego_type?: string | null;
  negoType?: string | null;
  payment_method?: string | null;
  paymentMethod?: string | null;
  region?: string | null;
  regionId?: string | null;
  district?: string | null;
  province_code?: string | null;
  provinceCode?: string | null;
  regency_code?: string | null;
  regencyCode?: string | null;
  district_code?: string | null;
  districtCode?: string | null;
  village?: string | null;
  cod_point?: string | null;
  codPoint?: string | null;
  store_maps_url?: string | null;
  storeMapsUrl?: string | null;
  seller_id?: string | null;
  sellerId?: string | null;
  seller_name?: string | null;
  sellerName?: string | null;
  seller_phone?: string | null;
  sellerPhone?: string | null;
  seller_avatar?: string | null;
  sellerAvatar?: string | null;
  seller?: {
    id?: string;
    name?: string;
    storeName?: string;
    phone?: string;
    avatar?: string;
  } | null;
  images?: string[] | null;
  status?: string | null;
  is_bu?: boolean | null;
  isBu?: boolean | null;
  bu_expires_at?: string | null;
  buExpiresAt?: string | null;
  qris_verified?: boolean | null;
  isQrisVerified?: boolean | null;
  views?: number | string | null;
  created_at?: string | null;
  createdAt?: string | null;
  updated_at?: string | null;
  updatedAt?: string | null;
}

export interface ListingCreateDTO {
  title: string;
  description: string;
  price: number;
  category: string;
  condition: string;
  nego_type: string;
  payment_method: string;
  region: string;
  district: string;
  province_code?: string | null;
  regency_code?: string | null;
  district_code?: string | null;
  village?: string | null;
  cod_point?: string;
  store_maps_url?: string;
  seller_id: string;
  seller_name: string;
  seller_phone?: string;
  seller_avatar?: string;
  images: string[];
  is_bu?: boolean;
  bu_expires_at?: string | null;
}
