-- Create a dedicated server-authoritative admin credential store.
-- Admin credentials must never be exposed through the browser or the public users table.

CREATE TABLE IF NOT EXISTS public.admin_users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  username text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'admin' CHECK (role = 'admin'),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS admin_users_username_lower_uidx
  ON public.admin_users (lower(username));

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;

-- Never expose admin credentials to browser roles.
REVOKE ALL ON TABLE public.admin_users FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.admin_users TO service_role;

COMMENT ON TABLE public.admin_users IS
  'Server-only admin accounts. Passwords are stored as scrypt hashes; browser roles have no access.';
COMMENT ON COLUMN public.admin_users.password_hash IS
  'scrypt password hash generated by scripts/generate-admin-password-hash.mjs';
